[package]
name = "image-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.14.2"
aws_lambda_events = "0.17.0"
aws-config = "1.8.2"
aws-sdk-s3 = "1.98.0"
image = "0.25"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4" 